full_name = "Nickolay Babenko"
description = "Nickolay is an engineer, crypto-entrepreneur, investor and bhakti-yogi. The combination of a technical mindset and deep understanding of the psychology of relationships helps him to to achieve ambitious and practical goals and secure long-standing relationships. Having 15 years of experience in the IT industry and 8 years specifically in blockchain industry, Nickolay is eager for new opportunities to make people happier in general and with the help of technology in particular. Previously to joining ThreeFold he co-founded one of the first bitcoin payment processors and multicurrency wallets."
why_threefold = "There are two reasons why I am here: 1. ThreeFold presents a completely new paradigm for the IT world and will change it as we know it today. 2. I admire people working on this project. It is the best team I have met in my whole life."
function = "Co-Founder"
linkedin= "https://www.linkedin.com/in/babenkonickolay/"
rank = 8
project_ids = [1,5]
contribution_ids = [1,3]
nationality = "Ukranian"
