full_name = "Raphael Zöscher"
description = "I am farmer in double sense - as a breeder of horses and as a part of the Threefold-grid. I am absolutely convinced about the Threefold technology and I want to become a Threefold speaker to share this revolutionary idea with people in Austria, Italy and France."
why_threefold = "I am farmer in double sense - as a breeder of horses and as a part of the Threefold-grid. I am absolutely convinced about the Threefold technology and I want to become a Threefold speaker to share this revolutionary idea with people in Austria, Italy and France."
function = "Ambassador"
linkedin= "https://www.linkedin.com/in/christian-seidl-56b22210/"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "St.Lorenzen, Austria"
