full_name = "Andrea Castiglione"
description = "For over a decade, Andrea has been working at the crossroad of technology, entrepreneurship and human relationships. Coming from a deeply analytical background, he has started multiple businesses and began investing in what he defines “digital emerging markets”, which in all essence, are companies designed to be digital and borderless; not bound by geography. As a venture builder, Andrea believes it’s time to reinvent the very architecture of the internet and he’s ready to support Threefold in distributing its technology and values through his experience and a global network of partners."
why_threefold = ""
function = ""
linkedin= "https://www.linkedin.com/in/castiglioneand/"
rank = 0
project_ids = [1]
contribution_ids = [1,3]
nationality = ""
