full_name = "Lawrence Bloom"
description = "Lawrence has taken profound initiation with the Kogi in Columbia and the pygmy in Gabon; with Sadhguru in Mt Kailash and HH the Dalai Lama in Dharamsala. He sat on the main board of the Intercontinental Hotel Group, created an environmental manual currently in use in over 5 million hotel rooms, Chaired a Global Agenda Council at the World Economic Forum at Davis, and a Green Cities, Buildings and Transport council for the Green Economy Initiative at the UN. And currently amongst other positions, he is Chairman of Be Energy a green energy company, Secretary General of Be Earth Foundation a UN recognised Intergovernmental Organisation, and co founder of a JV with Universal Music Group .."
why_threefold = "With a unique, realistic, and achievable solution to building a green, decentralised, distributed, and neutral IT infrastructure globally, committed to true values and charity, how can anyone not believe in the ThreeFold Foundation vision ?"
function = ""
linkedin= "https://www.linkedin.com/in/lawrence-bloom-3463a0/"
rank = 0
project_ids = [1]
contribution_ids = [1,3]
nationality = ""
